const productArray = [
  {
    productID: 1,
    productName: "Smartphone",
    categoryID: 1,
    brand: "Samsung",
    description: "High-end smartphone with advanced features.",
    price: 699.99,
    stockQuantity: 100,
    weight: 0.5,
    manufactureDate: "2023-01-15",
    expiryDate: null,
    averageRating: 4.5,
    numRatings: 120,
  },
  {
    productID: 2,
    productName: "Laptop",
    categoryID: 1,
    brand: "HP",
    description: "Powerful laptop for professional use.",
    price: 899.99,
    stockQuantity: 50,
    weight: 2.0,
    manufactureDate: "2023-02-10",
    expiryDate: null,
    averageRating: 4.8,
    numRatings: 80,
  },
  {
    productID: 3,
    productName: "Wireless Earbuds",
    categoryID: 2,
    brand: "Apple",
    description: "High-quality wireless earbuds with noise cancellation.",
    price: 199.99,
    stockQuantity: 200,
    weight: 0.1,
    manufactureDate: "2023-03-05",
    expiryDate: null,
    averageRating: 4.3,
    numRatings: 150,
  },
  {
    productID: 4,
    productName: "LED TV",
    categoryID: 3,
    brand: "Sony",
    description: "Ultra HD LED TV with smart features.",
    price: 1299.99,
    stockQuantity: 30,
    weight: 15.0,
    manufactureDate: "2023-02-20",
    expiryDate: null,
    averageRating: 4.7,
    numRatings: 60,
  },
];

export default productArray;
